package com.michael.wallpaper.dao.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table COLLECTED_BELLE.
 */
public class CollectedBelle {

    /** Not-null value. */
    private String url;
    private long time;
    private String rawUrl;
    private Integer width;
    private Integer height;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CollectedBelle() {
    }

    public CollectedBelle(String url) {
        this.url = url;
    }

    public CollectedBelle(String url, long time, String rawUrl, Integer width, Integer height) {
        this.url = url;
        this.time = time;
        this.rawUrl = rawUrl;
        this.width = width;
        this.height = height;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public String getRawUrl() {
        return rawUrl;
    }

    public void setRawUrl(String rawUrl) {
        this.rawUrl = rawUrl;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
