package com.michael.wallpaper.dao.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SERIES.
 */
public class Series implements java.io.Serializable {

    private int type;
    /** Not-null value. */
    private String title;
    private String category;
    private String tag3;
    private Integer property;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Series() {
    }

    public Series(int type, String title, String category, String tag3, Integer property) {
        this.type = type;
        this.title = title;
        this.category = category;
        this.tag3 = tag3;
        this.property = property;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getTag3() {
        return tag3;
    }

    public void setTag3(String tag3) {
        this.tag3 = tag3;
    }

    public Integer getProperty() {
        return property;
    }

    public void setProperty(Integer property) {
        this.property = property;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
